### ISSUE TITLE
OOM on preserve_distances for mnist

### ISSUE THREAD

**Issue by timsainb** [cvxgrp/pymde#1]
Hey all, 

I'm having trouble running preserve_distances on mnist because pymde tries to allocate 1000Gb of RAM. Is that to be expected? Thanks

```
Mar 22 10:57:27 PM: Sampling 50000000 edges
Mar 22 10:57:32 PM: Computing 50000000 distances
 RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 156800000000 bytes. Error code 12 (Cannot allocate memory) 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-f2ac8e7c8297> in <module>
----> 1 z = pymde.preserve_distances(X_train, verbose=True).embed()

~/anaconda3/envs/tfumap/lib/python3.7/site-packages/pymde/recipes.py in preserve_distances(data, embedding_dim, loss, constraint, max_distances, device, verbose)
    106 
    107     graph = preprocess.generic.distances(
--> 108         data, retain_fraction=retain_fraction, verbose=verbose
    109     )
    110     edges = graph.edges.to(device)

~/anaconda3/envs/tfumap/lib/python3.7/site-packages/pymde/preprocess/generic.py in distances(data, retain_fraction, verbose)
     50     if _is_data_matrix(data):
     51         return data_matrix.distances(
---> 52             data, retain_fraction=retain_fraction, verbose=verbose
     53         )
     54     else:

~/anaconda3/envs/tfumap/lib/python3.7/site-packages/pymde/preprocess/data_matrix.py in distances(data, retain_fraction, verbose)
     79         # and/or the number of features is large.
     80         delta = (
---> 81             (data[edges[:, 0]] - data[edges[:, 1]])
     82             .pow(2)
     83             .sum(dim=1)

RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 156800000000 bytes. Error code 12 (Cannot allocate memory)
```

**Comment by timsainb** [comment]
Decreasing max_distances by 1-2 orders of magnitude allows me to embed, but the embeddings don't seem to capture much structure.

**Comment by akshayka** [comment]
Thanks for trying out PyMDE!

As you've seen the `max_distances` parameter can be used to control the number of distances that will be preserved/sampled. If your features are very high-dimensional, computing the original distances can take a lot of RAM. The current implementation tries to compute all these distances at once (see line 81 in the stack trace you pasted); in a future version we can batch this computation, to minimize the chances that an OOM occurs.

It looks like you're working an original (dense?) data matrix.  What's the size of this matrix?

In our experience the `preserve_distances` method can capture coarse global structure, but does not always capture fine local structure (such as clusters of similar items). It's possible that the number of distances you're computing is too small for anything interesting to arise. You might also check that the original data has been preprocessed so that the original distances are actually meaningful (e.g., you might consider standardizing the data before passing it to `preserve_distances`).

If you can share your code/data (eg, as a Python notebook), I'd be happy to work with you towards getting a better embedding.

**Comment by akshayka** [comment]
I should mention: the Euclidean distance (which is what `preserve_distances` uses to compute the original distances, when you give it an original data matrix) is not a good global metric on images, but it is a good local one (which is why `preserve_neighbors` works well for MNIST). 
In particular, two images with large Euclidean distance might be similar, e.g., if one is a translation or rotation of the other, but two images with small Euclidean distance are surely similar.

For this reason it's not entirely surprising that `preserve_distances` would not work well on MNIST. If you really wanted to preserve original distances globally for image datasets, it might be interesting to experiment with other notions of original distance, such as the Earth-mover's distance. The `preserve_distances` method does not yet have support for other distance functions, but if you compute the distances yourself, you could create your own `MDE` problem that was designed to preserve them. 

Another option is to compute a k-nearest neighbor graph of MNIST, and pass that graph to `preserve_distances`. When given a graph, `preserve_distances` will use the shortest-path metric as the original distance. This might yield a more interesting embedding. I can give you code that does this.

**Comment by timsainb** [comment]
Thanks @akshayka I'd be interested in the shortest path metric if you have code!

**Comment by akshayka** [comment]
@timsainb , sorry for the delay!

I put together a notebook showing how to use the shortest path metric, w/MNIST as the example: https://colab.research.google.com/drive/1JTmy55IFRcdeAPLXS_Sk69j52R-5KvDQ?usp=sharing

Using a small subset of MNIST, and using the most basic loss function (a quadratic) to preserve shortest paths, I get the following embedding, which seems reasonable

![image](https://user-images.githubusercontent.com/1994308/113088505-907c7a00-919a-11eb-8d42-e06758bd86d1.png)

The preprocessing functions used in that notebook are documented here: https://pymde.org/api/index.html#preprocessing

It could be fun to play around with the parameters in that notebook, to explore how different preprocessing steps / different distortion functions affect the embedding. Let me know if you have any questions!

**Comment by timsainb** [comment]
Thanks, I'll play around with it. Awesome paper/repo!
